### ISSUE TITLE
How to set currency exchange rate , default APIs returning only USD

### ISSUE THREAD

**Issue by SmokyTyrz** [bradjasper/CryptocurrencySpreadsheetUtils#12]
Hi

First, thank you so much for this add on. It is very, very useful!!  

Is there a simple way to tweak the plug in to return coin prices in something other than USD?   I found the price_usd attributes but when called for another currency my metrics begin to fail.  Am I missing a switch somewhere?  I'd like to find all of the switches so I can programmatically control the currency exchange rate shown within the UI. 

Thank you!

**Comment by SmokyTyrz** [comment]
Hi again

Just wanted to make a second try to see if there was a straightforward way to return non USD coin prices?

**Comment by bradjasper** [comment]
Hello, currently there's not a convenient way to do this. It might be possible to build this in for a specific exchange, but better support probably better to create a simple API that can be implemented separately.

This is definitely something I'd like to add, I hope to get some time for it soon, or if anyone else wants to try I'd be happy to accept a pull request.

**Comment by SmokyTyrz** [comment]
Thanks!  I would also be very interested in this!
