### ISSUE TITLE
How to add a proxy?

### ISSUE THREAD

**Issue by pauljamesgo** [bradjasper/CryptocurrencySpreadsheetUtils#2]
Hi Everyone,

Firstly, I want to thank you for this. 

Secondly, I just want to ask on how to add a proxy on the function for our company requires JIRA to be access inside the company's network.

Warm regards,
Paul

**Comment by bradjasper** [comment]
Hello, the utils use the UrlFetchApp class from Google: https://developers.google.com/apps-script/reference/url-fetch/url-fetch-app

Unfortunately I don't see a way to add a proxy to this. Are the requests failing and being blocked by your network?
