### ISSUE TITLE
stopped working for smaller coins

### ISSUE THREAD

**Issue by max-pain** [bradjasper/CryptocurrencySpreadsheetUtils#3]
it seems to have stopped working. it doesn't get the values anymore for smaller coins.

try:
CREA and HMQ

**Comment by Mwisho** [comment]
You can easily fix this, on rule 292 change:

`return this.url + "ticker";`

to:

`return this.url + "ticker/?limit=0";`

and then it should work again!

**Comment by max-pain** [comment]
thank you

**Comment by bradjasper** [comment]
Thanks for the fix and pull request!
