### ISSUE TITLE
Special case when two coins have the same symbol

### ISSUE THREAD

**Issue by jeromedalbert** [bradjasper/CryptocurrencySpreadsheetUtils#5]
In Coinmarketcap, `BTG` is the symbol for both [Bitcoin Gold](https://coinmarketcap.com/currencies/bitcoin-gold/) and [Bitgem](https://coinmarketcap.com/currencies/bitgem/).

I want to track Bitcoin Gold, but `getCoinPrice('BTG')` returns the price for Bitgem instead. Bad luck! I know this is an edge case, but yesterday Bitcoin Gold made it to the top 5 currencies in Coinmarketcap, so we should probably find a solution soon as it is getting more famous and more people will want to track it.

Here are a few suggestions about how to deal with this:
1. Always return the coin with the highest market cap when there is ambiguity (in this case Bitcoin Gold). Possible fix in PR #6.
1. Being able to select the exact coin we want without ambiguity. Could be via a new function, or a param in `getCoinPrice`. Selecting the coin via name is probably the best solution, since using a numeric index may not guarantee the same result because of sorting.

**Comment by bradjasper** [comment]
Thanks for the pull request! I've merged it in and made note to handle this better in the future. I think the getCoinPrice function could either take the full name of a coin or the symbol.

**Comment by jeromedalbert** [comment]
Yeah, being able to do either `getCoinPrice('BTG')` or `getCoinPrice('Bitcoin Gold')` would be best. Since this solution implies deeper refactoring, I didn't want to tackle it. 😄

**Comment by jeromedalbert** [comment]
@bradjasper the "same coin problem" happened again with GTC 😄 . I want to track my bought https://coinmarketcap.com/currencies/game (which has an unknown market cap as of yet), but instead it tracks https://coinmarketcap.com/currencies/global-tour-coin which has a bigger market cap.

I guess I could wait a bit, since game will probably have a higher market cap when it becomes known. In the meantime if the pressure to track my coins ASAP is too high, maybe I can help with a pull request. If you have any directions on what you would want the feature to be like, that could be useful.

**Comment by jeromedalbert** [comment]
Here are some ideas but I just thought about it for 10 seconds:

- allow `getCoinPrice('BTG')` or `getCoinPrice('Bitcoin Gold')` interchangeably. It would look up the name first, then the symbol. Or the contrary.
- make a breaking change to the `CryptocurrencySpreadsheetUtils` API, where you could do `getCoinPrice({ symbol: 'BTG' })` or `getCoinPrice({ name: 'Bitcoin Gold' })`
- keep the old `getCoinPrice('BTG')` way, but allow `getCoinPrice({ name: 'Bitcoin Gold' })` API too. I.e. if the first param is an object, use the new API; otherwise use the old one.
